### ISSUE TITLE
[AVM Question/Feedback]: AVM Targeting Multiple subscriptions

### ISSUE THREAD

**Issue by eamreyes** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#147]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I recently started using AVM modules for TF and I have a question about how the peering module is able to target multiple subscriptions (ex: Hub Network is in a Platform LZ subscription and Spoke Network is in another subscription).

I expected to have to use TF aliases, but the module appears to use azapi to allow one Service Principal to target multiple subscriptions. Is using azapi the established pattern for all AVM Modules? Is there a community call or documentation that can provide more background on the decision?

Thanks.

**Comment by jaredfholgate** [comment]
Hi. We use `azurerm` or `azapi` interchangeably depending on the needs of the module. Both providers are fully supported by Microsoft. Using AzAPI enables us to target new features sooner and handle cases like the cross subscription peering you mention gracefully.

We mention this in our spec here: https://azure.github.io/Azure-Verified-Modules/specs/terraform/

```
Provider Versatility: Users have the autonomy to choose between AzureRM, AzAPI, or a combination of both, tailored to the specific complexity of module requirements.
```

Moving forward we are going to include more advice about when module authors should use AzAPI (given the features in v2.0) and also provide advice around other providers (e.g. azuread, github, azuredevops, etc). You should check out the HashiConf session when it is available to learn more: https://www.hashicorp.com/conferences/hashiconf/agenda/10-15/unlocking-the-latest-innovations-in-terraform-on-azure

Closing this for now, since it is just a question.
