### ISSUE TITLE
[AVM Module Issue]: Why is resource "azapi_resource" "vnet" being used instead of azurerm_virtual_network Terraform resource

### ISSUE THREAD

**Issue by ritesh-modi** [Azure/terraform-azurerm-avm-res-network-virtualnetwork#169]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

The current module is using azapi_resource to provision a virtual network. What is the compelling reason to use azapi_resource instead of azurerm_virtual_network Terraform resource. It would be lot better and predicatable to use azurerm_virtual_network Terraform resource rather than azapi_resource. Can you provide some insights on this?

**Comment by jaredfholgate** [comment]
With regards to using azapi, it we originally made that change to meet customer requirements. One example being customers that have a DENY policy on creating a subnet without an NSG. This is impossible with azurerm since it creates the subnet and assigns the NSG in two separate operations, whereas azapi creates the subnet with the NSG in a single operation. We also wanted to support cross subscription peering in a single module, which is also not possible with azurerm.

Given this is a question and we are have no plans to revert back to azurerm, I will close this for now.

I am helping the author with their actual problem on an internal chat.
